FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
COPY apps/price-service/package*.json ./apps/price-service/
RUN npm ci
COPY . .
WORKDIR /app/apps/price-service
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/apps/price-service/dist ./dist
COPY --from=build /app/apps/price-service/package*.json ./
RUN npm ci --omit=dev
EXPOSE 3001
CMD ["node", "dist/server.js"]
