[build]
  base    = "netlify"
  publish = "netlify/public"
  command = "bash ./netlify-build.sh"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-cache"
[build.environment]
  NODE_VERSION = "20.18.1"
  NPM_FLAGS = "--no-audit --no-fund"
