[build]
base = "apps/frontend"
publish = "build"
command = "npm ci && npm run build"

[build.environment]
NODE_VERSION = "20"
NPM_FLAGS = "--legacy-peer-deps"

[functions]
node_bundler = "esbuild"

[context.production.environment]
NODE_ENV = "production"

[context.deploy-preview]
command = "npm ci && npm run build"

[build.processing]
skip_processing = true