[build]
base = "apps/frontend"
publish = "build"
command = "npm ci --legacy-peer-deps && npm run build"

[build.environment]
NODE_VERSION = "20"
NPM_FLAGS = "--legacy-peer-deps"
NPM_CONFIG_PRODUCTION = "false"
CI = "false"

[context.deploy-preview]
command = "npm ci --legacy-peer-deps && npm run build"

[build.processing]
skip_processing = true
