[build]
  base = "apps/frontend"
  command = "npm install && npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3001/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200