name: Autofix + Check
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Prettier (auto-fix)
        run: npx --yes prettier . -w || true

      - name: ESLint (nur wenn Config existiert)
        run: |
          if ls -1 .eslintrc* eslint.config.* >/dev/null 2>&1; then
            npx --yes eslint . --fix || true
          else
            echo "kein ESLint-Config gefunden → übersprungen"
          fi

      - name: npm audit fix (nur wenn package.json im Root)
        run: |
          if [ -f package.json ]; then npm ci || true; npm audit fix || true; else echo "kein package.json → übersprungen"; fi

      # Workflows niemals committen: Änderungen verwerfen
      - name: Revert workflow changes
        run: |
          git checkout -- .github/workflows || true

      # Nur Nicht-Workflow-Dateien committen
      - name: Commit fixes (Workflows ausschließen)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: auto-fix (prettier/eslint/npm-audit)"
          branch: ${{ github.head_ref || github.ref_name }}
          file_pattern: |
            .
            :!./.github/**
